# Generated by Django 4.1.7 on 2023-05-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbermovie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='numberseries',
            name='name',
        ),
    ]
