# Generated by Django 4.1.7 on 2023-05-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_numbermovie_name_remove_numberseries_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbermovie',
            name='numbermovie',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='numberseries',
            name='numberseries',
            field=models.CharField(max_length=20),
        ),
    ]
